### ISSUE TITLE
Option to disable 8-bit font?

### ISSUE THREAD

**Issue by able16** [marconsou/deep-dungeon-tracker#2]
8-bit font is kind of distracting when you want to glance over for information quickly. 

![image](https://user-images.githubusercontent.com/3988186/213605429-80c1f74c-8bd1-41cd-af01-359da1c87317.png)

**Comment by marconsou** [comment]
I'm not sure what do you mean by disabling the font, but I going to suggest few things that might help:

- Try to not scale down the size of window too much because depending of the resolution it will not look good. Keep the Scale at 1.0.
- If you are struggling with the size of the Window on the screen, in this case is better to keep the size at 1.0 and hide some fields (or even a entire column)

![Window](https://user-images.githubusercontent.com/27457164/213612300-90464387-3293-428d-8ba0-1bc280125c7a.png)

**Comment by able16** [comment]
Disabling the 8-bit font meaning to have it display Tracker and Score Window information in regular font. Like the Timer Window. 
![image](https://user-images.githubusercontent.com/3988186/213661678-9f380322-c33f-4da2-a17b-96265a073a12.png)

**Comment by marconsou** [comment]
I started some initial testing, but I not sure yet...
![Test](https://user-images.githubusercontent.com/27457164/213776292-af0676ab-7227-4a87-a1e8-08d4e4a2fc82.png)

**Comment by able16** [comment]
That's exactly what I had in mind. Maybe if it could inherit the floor/set/total colors as well. Also noting for the change on the Score Window as well (plus comma separators).
