### ISSUE TITLE
Feature: Assume +99/+99 Aetherpool

### ISSUE THREAD

**Issue by syldrathecat** [marconsou/deep-dungeon-tracker#4]
I was trying to compare the score at different points in two runs and I noticed that because I forge grips and start the runs without the max aetherpool level, the calculated score differs depending on a snapshot of whatever aetherpool levels I happened to have at the end of the most recent set in a run.

Could a "Last Floor (assume +99/+99 aetherpool)" scoring calculation mode be added that assumes that you will reach maximum aetherpool levels before clearing the run, and removes that as a variable?

**Comment by syldrathecat** [comment]
Specifically, I was trying to compare two different in-progress runs at floor 40, but the difference in score was primarily dominated by my current aetherpool levels instead of the actual value gained in the run.

Since the "Last Floor" mode calculation mode is supposed to represent the score as if you had the current kills/chests/traps going in to floor 100, it makes more sense to me if also factored in the inevitable max aetherpool level I'd get.

e.g.

![image](https://user-images.githubusercontent.com/13056379/231527905-bbae4172-1a59-47af-b82c-f01777233fc5.png)

The top run is clearly not worth 13k extra score compared to the bottom, I just happened to start it with a slightly higher aetherpool level.

**Comment by marconsou** [comment]
This is a very specific situation. I don't know what is in your Aetherpool right now.
I'm going to give you an example of what you can do in this case:
These are the values that Aetherpool affects (at +99):
![99](https://user-images.githubusercontent.com/27457164/231540545-463d6663-fc9b-43e0-a18c-969aa41d9d2f.png)
And this is for +89 (an example).
![89](https://user-images.githubusercontent.com/27457164/231540885-ad424f55-0975-4e6a-8a4a-f8c3d46de166.png)

The green values you see are written in the file in exactly the same way you see them on the screen. Changing other values, such as kills, will not change those values.
The yellow (or light blue, in case you click one of those sets) will change dynamically if you change your Aetherpool directly on the file.

So, in this case specifically, if you want to compare both files, you need to click on the "031-40" Set on your +99/+99 file.
For your reduced aetherpool file, you're going to need to edit the file directly, increasing your aetherpool (arm and armor) to 99.
Then you need to look at the yellow/light blue values on the right side of the screen (forget about the green ones because they are not going to change).
You're going to be able to see the difference.

**Comment by marconsou** [comment]
Both **Score Window Floor** and **Last Floor** will work as Aetherpool at max level.
The **Current Floor** will work as it does now (the current Aetherpool).
So, that should cover both situations for now.
